# Grants the Jenkins service account cluster-wide permissions
# (across all namespaces) to deploy and modify Kubernetes resources
# (needed for pulling and deploying images from ecommerce-registry)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-deployer
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
