apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-container
          image: registry.ecommerce.local:5000/ecommerce-product-service:0.5.3
          ports:
            - containerPort: 9090
          env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: product-db-config  # Reference ConfigMap
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: product-db-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: product-db-secret  # Reference Secret
                key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: product-app
  ports:
    - protocol: TCP
      port: 9090         # The service port accessible inside the cluster (and via NodePort externally)
      targetPort: 8761   # The container port the service maps to
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-ingress
  namespace: ecommerce
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 9090